### ISSUE TITLE
Improvements propositions

### ISSUE THREAD

**Issue by Universal-Rom-Tools** [NeeeeB/GameList_Editor#1]
Your soft is great ;)

I use it specifically to check my scrape ;) and it works very well :D 

My 2 cents : 

Duplicate Research : 

You use Scrape from UXS, UXS take the game ID form ScreenScraper and put it as value in XML.
So you can add a "filter" to sort by this ID and select only duplicate ID ;)
This way you can easily found Duplicate game.

Refresh : 

To refesh the "System list" you must re-select the folder, a simple "Reload" in menu can do it easily ;)

**Comment by NeeeeB** [comment]
Thanks ;-)

I had this option at the very beginning (use the game ID) but some systems are not scraped with this ID, like Mame, and I further removed it. Maybe I'll consider adding it back but need to do it properly as I like square things ^^

Your second proposition is a really good idea, totally didn't think to it.
Will try to add it tomorrow if I have a little bit of free time.

Thanks for your propositions.
PS: You are Screech btw, aren't you ? might be easier to join me on Recalbox forum if needed ^^

**Comment by Universal-Rom-Tools** [comment]
Yes I am ;)

Just not so much time to be on IRC ;)

(And it's to make so life on your Issue channel :p )

**Comment by NeeeeB** [comment]
Ahah, yeah sorry if there are no issues to report ^^
Looking forward to add your propositions ;-)

Le 24 nov. 2017 20:12, "Universal ROM Tools" <notifications@github.com> a
écrit :

**Comment by NeeeeB** [comment]
Reload menu is implemented.
GameID is on the ToDo list.
